### ISSUE TITLE
Feature Request: Remove AzureFirewallSubnet when not Deploying Azure Firewall

### ISSUE THREAD

**Issue by jonathan-vella** [Azure/data-management-zone#216]
For deployments which do not require Azure Firewall, we should remove the automated deployment of the AzureFirewallSubnet.
There's no use for this /24 subnet.

**Comment by marvinbuss** [comment]
Hi @jonathan-vella,
Thanks for submitting this. I am currently evaluating the best way to implement this feature request. Due to the issue described here https://github.com/Azure/bicep/issues/2733 there is no clean way of implementing this. We wither define each subnet as variable and then do a concat or we leave things as they are for now and then customers can remove subnets from the IaC if they are not required.

For the Management Zone, it is still quite easy, but for the Data Landing Zone it will get more messy as more subnets are created. Also, I want to make sure that we are consistent across Data Management Zone and Data Landing Zone. Do you have any preference wrt the options mentioned above?
Looking forward to your feedback!

**Comment by marvinbuss** [comment]
Hi @jonathan-vella,
Feel free to take a look at https://github.com/Azure/data-management-zone/pull/219 and share your thoughts.

**Comment by jonathan-vella** [comment]
Sure. Please allow me some time since I'm travelling all week this week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
